[deployment]
pattern = "DEV"

[super_admin]
username = "admin"
password = "admin"

[user_store]
type = "read_write_ldap"
connection_url = "ldap://ldap.example.com:389"
connection_name = "uid=admin,ou=wso2is"
connection_password = "$secret{ldap_password}"
base_dn = "dc=example,dc=com"
class = "org.wso2.carbon.user.core.ldap.ReadWriteLDAPUserStoreManager"
tenant_manager  =  "org.wso2.carbon.user.core.tenant.CommonHybridLDAPTenantManager"
anonymous_bind  =  false
user_search_base  =  "ou"
user_entry_object_class  =  "identityPerson"
user_name_attribute  =  "uid"
user_name_search_filter  =  "(&amp;(objectClass=person)(uid=?))"
user_name_list_filter  =  "(objectClass=person)"
display_name_attribute  =  ""
read_groups  =  true
write_groups  =  true
group_search_base  =  "ou=Groups,dc=wso2,dc=org"
group_entry_object_class  =  "groupOfNames"
group_name_attribute  =  "cn"
group_name_search_filter  =  "(&amp;(objectClass=groupOfNames)(cn=?))"
group_name_list_filter  =  "(objectClass=groupOfNames)"
membership_attribute  =  "member"
back_links_enabled  =  false
scim_enabled  =  true
is_bulk_import_supported  =  true
empty_roles_allowed  =  true
password_hash_method  =  "PLAIN_TEXT"
multi_attribute_separator  =  ","
max_user_name_list_length  =  100
max_role_name_list_length  =  100
kdc_enabled  =  false
default_realm_name  =  "WSO2.ORG"
user_roles_cache_enabled  =  true
connection_pooling_enabled  =  false
ldap_connection_timeout  =  5000
read_timeout   =   ""
retry_attempts   =   ""
start_tls_enabled  =  false
username_java_regex  =  "[a-zA-Z0-9._\-|//]{3,30}$"
rolename_java_regex  =  "[a-zA-Z0-9._\-|//]{3,30}$"
username_javascript_regex = "^[\S]{3,30}$"
username_java_regex_violation_error_msg = "Username pattern policy violated"
password_java_regex = "^[\S]{5,30}$"
password_javascript_regex = "^[\S]{5,30}$"
password_java_regex_violation_error_msg = "Password length should be within 5 to 30 characters"
rolename_javascript_regex = "^[\S]{3,30}$"

[secrets]
ldap_password = "encrypted_value_1"
