[deployment]
pattern = "DEV"
hostname = "localhost"

[super_admin]
username = "admin"
password = "admin"

[user_store]
type = "read_only_ldap"
connection_url = "ldap://ldap.example.com:389"
connection_name = "uid=admin,ou=wso2is"
connection_password = "$secret{ldap_password}"
base_dn = "dc=example,dc=com"
class = "org.wso2.carbon.user.core.ldap.ReadOnlyLDAPUserStoreManager"
tenant_manager  =  "org.wso2.carbon.user.core.tenant.CommonHybridLDAPTenantManager"
anonymous_bind  =  false
user_search_base  =  "ou=system"
user_name_attribute  =  "uid"
user_name_search_filter  =  "(&amp;(objectClass=person)(uid=?))"
user_name_list_filter  =  "(objectClass=person)"
display_name_attribute  =  ""
read_groups  =  true
group_search_base  =  "ou=system"
group_name_attribute  =  "cn"
group_name_search_filter  =  "(&amp;(objectClass=groupOfNames)(cn=?))"
group_name_list_filter  =  "(objectClass=groupOfNames)"
membership_attribute  =  "member"
back_links_enabled  =  false
scim_enabled  =  false
password_hash_method  =  "PLAIN_TEXT"
multi_attribute_separator  =  ","
max_user_name_list_length  = 100
max_role_name_list_length  =  100
user_roles_cache_enabled  =  true
connection_pooling_enabled  =  true
ldap_connection_timeout  =  5000
read_timeout  =  ""
retry_attempts  =  ""
replace_escape_characters_at_user_login  =  true
username_java_regex = "[a-zA-Z0-9._\-|//]{3,30}$"
rolename_java_regex = "[a-zA-Z0-9._\-|//]{3,30}$"
password_java_regex = "^[\S]{5,30}$"

[secrets]
ldap_password = "encrypted_value_1"
